import { AppHeader } from './components/AppHeader'
import { StudyPage } from './pages/StudyPage'

export default function App() {
  return (
    <>
      <a className="skip-link" href="#main">
        Skip to content
      </a>
      <AppHeader />
      <StudyPage />
      <footer className="app-footer">
        Answers are generated by AI from your PDF. Always double-check important details.
      </footer>
    </>
  )
}
